version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    server:
        build: ./server
        ports:
            - "80:80"
        links:
            - db
        volumes:
            - "${DOCKER_DIR}:/var/www/symfony"
        tmpfs:
            - /tmp
            - /var/www/symfony/var/cache
            - /var/run
    phpmyadmin:
        build: ./phpmyadmin
        ports:
            - "82:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
